package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name = "candidate", catalog = "trmsv2_hr_sales", uniqueConstraints = {
		@UniqueConstraint(columnNames = "contact_no"), @UniqueConstraint(columnNames = "email_id") })
public class Candidate implements java.io.Serializable {

	/**
	 *serialVersionUID 
	 */
	private static final long serialVersionUID = -5851121953026325865L;
	
	private int candidateId;
	private String candidateName;
	private String contactNo;
	private String emailId;
	private String otherContactdetails;
	private String service;
	private Date enrollmentDate;
	private String enrollmentFormStatus;
	private String transactionId;
	private BigDecimal totalAmount;
	private BigDecimal amountPaid;
	private BigDecimal amountDue;
	private Date dueDate;
	private Date offeretterSendDate;
	private Date treminationDate;
	private String emergencyContactDetails;
	private String primarySkill;
	private Date trainingStartDate;
	private Date trainingExpectedEndDate;
	private String batchCode;
	private String trainingStatus;
	private String trainingFeedback;
	private Date trainingFeedbackFormSendDate;
	private Date trainingFeedbackReceiveDate;
	private Date cebTestSendDate;
	private Date cebTestCompleteDate;
	private String cebTestResult;
	private Date resumeDocSendDate;
	private Date resumeDocReceiveDate;
	private String visaStory;
	private Date techMockScheduleDate;
	private Date techMockEndDate;
	private Date mockScheduleDate;
	private Date mockEndDate;
	private Date psrSentDate;
	private Date psrReceiveDate;
	private Date questionerSentDate;
	private Date questionerReceiveDate;
	private Date graduationScheduleDate;
	private Date graduationEndDate;
	private String attendees;
	private String feedback;
	private String actionRequired;
	private String alternativePhone;
	private String yearsOfExperience;
	private String currentLoc;
	private String preferredLoc;
	private String visaStatus;
	private String availability;
	private String priority;
	private Date dateOnHotlist;
	private String domain;
	private Date referenceFormSentDate;
	private Date referenceFormReceivedDate;
	private Boolean referenceCheckStatus;
	private Date tentativeTrainingStartDate;
	private Date paymentDate;
	private String paymentMode;
	private String referenceFormNo;
	private String trainerName;
	private String trainingTiming;
	private Date resumeRevisedDate;
	private String alternateEmailId;
	private Boolean hotlistStatus;
	private Date receivingEnrollmentDate;
	private Date employmentLetterStartDate;
	private String hotlistCandidateName;
	private String resumePrepStatus;
	private String mockStatus;
	private String recruiterName;
	private String incentivePaidStatus;
	private String trainingWebexAccount;
	private Date sendingEnrollmentDate;
	private String supervisorName;
	private String enrollmentFormPath;
	private String resumePath;
	private String enrollmentFormFileExtension;
	private String resumeFileExtension;
	private String enrollmentFormName;
	private String resumeFileName;
	private Boolean isRemoveFromHotlist;
	private String billRate;
	private String hotlistStatusPredefine;
	private Date enrollmentNextFollowupDate;
	private Date trainingNextFollowupDate;
	private Date resumeNextFollowupDate;
	private Date mockNextFollowupDate;
	private Date referenceNextFollowupDate;
	private Date preHotlistNextFollowupDate;
	private Date importedDate;
	private String isTerminated;
	private String terminatedFrom;
	private String terminationReason;
	private Set<SalesFollowUp> salesFollowUps = new HashSet<SalesFollowUp>(0);
	private Set<Reference> references = new HashSet<Reference>(0);
	private Set<Documents> documentses = new HashSet<Documents>(0);
	private Set<Priority> priorities = new HashSet<Priority>(0);
	private Set<HrFollowUp> hrFollowUps = new HashSet<HrFollowUp>(0);
	private Set<InterviewSchedule> interviewSchedules = new HashSet<InterviewSchedule>(0);
	private Set<PaymentTransaction> paymentTransactions = new HashSet<PaymentTransaction>(0);
	private Set<MailDetails> mailDetailses = new HashSet<MailDetails>(0);

	public Candidate() {
	}

	public Candidate(int candidateId, String candidateName, String contactNo, String emailId) {
		this.candidateId = candidateId;
		this.candidateName = candidateName;
		this.contactNo = contactNo;
		this.emailId = emailId;
	}

	public Candidate(int candidateId, String candidateName, String contactNo, String emailId,
			String otherContactdetails, String service, Date enrollmentDate, String enrollmentFormStatus,
			String transactionId, BigDecimal totalAmount, BigDecimal amountPaid, BigDecimal amountDue, Date dueDate,
			Date offeretterSendDate, Date treminationDate, String emergencyContactDetails, String primarySkill,
			Date trainingStartDate, Date trainingExpectedEndDate, String batchCode, String trainingStatus,
			String trainingFeedback, Date trainingFeedbackFormSendDate, Date trainingFeedbackReceiveDate,
			Date cebTestSendDate, Date cebTestCompleteDate, String cebTestResult, Date resumeDocSendDate,
			Date resumeDocReceiveDate, String visaStory, Date techMockScheduleDate, Date techMockEndDate,
			Date mockScheduleDate, Date mockEndDate, Date psrSentDate, Date psrReceiveDate, Date questionerSentDate,
			Date questionerReceiveDate, Date graduationScheduleDate, Date graduationEndDate, String attendees,
			String feedback, String actionRequired, String alternativePhone, String yearsOfExperience,
			String currentLoc, String preferredLoc, String visaStatus, String availability, String priority,
			Date dateOnHotlist, String domain, Date referenceFormSentDate, Date referenceFormReceivedDate,
			Boolean referenceCheckStatus, Date tentativeTrainingStartDate, Date paymentDate, String paymentMode,
			String referenceFormNo, String trainerName, String trainingTiming, Date resumeRevisedDate,
			String alternateEmailId, Boolean hotlistStatus, Date receivingEnrollmentDate,
			Date employmentLetterStartDate, String hotlistCandidateName, String resumePrepStatus, String mockStatus,
			String recruiterName, String incentivePaidStatus, String trainingWebexAccount, Date sendingEnrollmentDate,
			String supervisorName, String enrollmentFormPath, String resumePath, String enrollmentFormFileExtension,
			String resumeFileExtension, String enrollmentFormName, String resumeFileName, Boolean isRemoveFromHotlist,
			String billRate, String hotlistStatusPredefine, Date enrollmentNextFollowupDate,
			Date trainingNextFollowupDate, Date resumeNextFollowupDate, Date mockNextFollowupDate,
			Date referenceNextFollowupDate, Date preHotlistNextFollowupDate, Date importedDate, String isTerminated,
			String terminatedFrom, String terminationReason, Set<SalesFollowUp> salesFollowUps,
			Set<Reference> references, Set<Documents> documentses, Set<Priority> priorities,
			Set<HrFollowUp> hrFollowUps, Set<InterviewSchedule> interviewSchedules,
			Set<PaymentTransaction> paymentTransactions, Set<MailDetails> mailDetailses) {
		this.candidateId = candidateId;
		this.candidateName = candidateName;
		this.contactNo = contactNo;
		this.emailId = emailId;
		this.otherContactdetails = otherContactdetails;
		this.service = service;
		this.enrollmentDate = enrollmentDate;
		this.enrollmentFormStatus = enrollmentFormStatus;
		this.transactionId = transactionId;
		this.totalAmount = totalAmount;
		this.amountPaid = amountPaid;
		this.amountDue = amountDue;
		this.dueDate = dueDate;
		this.offeretterSendDate = offeretterSendDate;
		this.treminationDate = treminationDate;
		this.emergencyContactDetails = emergencyContactDetails;
		this.primarySkill = primarySkill;
		this.trainingStartDate = trainingStartDate;
		this.trainingExpectedEndDate = trainingExpectedEndDate;
		this.batchCode = batchCode;
		this.trainingStatus = trainingStatus;
		this.trainingFeedback = trainingFeedback;
		this.trainingFeedbackFormSendDate = trainingFeedbackFormSendDate;
		this.trainingFeedbackReceiveDate = trainingFeedbackReceiveDate;
		this.cebTestSendDate = cebTestSendDate;
		this.cebTestCompleteDate = cebTestCompleteDate;
		this.cebTestResult = cebTestResult;
		this.resumeDocSendDate = resumeDocSendDate;
		this.resumeDocReceiveDate = resumeDocReceiveDate;
		this.visaStory = visaStory;
		this.techMockScheduleDate = techMockScheduleDate;
		this.techMockEndDate = techMockEndDate;
		this.mockScheduleDate = mockScheduleDate;
		this.mockEndDate = mockEndDate;
		this.psrSentDate = psrSentDate;
		this.psrReceiveDate = psrReceiveDate;
		this.questionerSentDate = questionerSentDate;
		this.questionerReceiveDate = questionerReceiveDate;
		this.graduationScheduleDate = graduationScheduleDate;
		this.graduationEndDate = graduationEndDate;
		this.attendees = attendees;
		this.feedback = feedback;
		this.actionRequired = actionRequired;
		this.alternativePhone = alternativePhone;
		this.yearsOfExperience = yearsOfExperience;
		this.currentLoc = currentLoc;
		this.preferredLoc = preferredLoc;
		this.visaStatus = visaStatus;
		this.availability = availability;
		this.priority = priority;
		this.dateOnHotlist = dateOnHotlist;
		this.domain = domain;
		this.referenceFormSentDate = referenceFormSentDate;
		this.referenceFormReceivedDate = referenceFormReceivedDate;
		this.referenceCheckStatus = referenceCheckStatus;
		this.tentativeTrainingStartDate = tentativeTrainingStartDate;
		this.paymentDate = paymentDate;
		this.paymentMode = paymentMode;
		this.referenceFormNo = referenceFormNo;
		this.trainerName = trainerName;
		this.trainingTiming = trainingTiming;
		this.resumeRevisedDate = resumeRevisedDate;
		this.alternateEmailId = alternateEmailId;
		this.hotlistStatus = hotlistStatus;
		this.receivingEnrollmentDate = receivingEnrollmentDate;
		this.employmentLetterStartDate = employmentLetterStartDate;
		this.hotlistCandidateName = hotlistCandidateName;
		this.resumePrepStatus = resumePrepStatus;
		this.mockStatus = mockStatus;
		this.recruiterName = recruiterName;
		this.incentivePaidStatus = incentivePaidStatus;
		this.trainingWebexAccount = trainingWebexAccount;
		this.sendingEnrollmentDate = sendingEnrollmentDate;
		this.supervisorName = supervisorName;
		this.enrollmentFormPath = enrollmentFormPath;
		this.resumePath = resumePath;
		this.enrollmentFormFileExtension = enrollmentFormFileExtension;
		this.resumeFileExtension = resumeFileExtension;
		this.enrollmentFormName = enrollmentFormName;
		this.resumeFileName = resumeFileName;
		this.isRemoveFromHotlist = isRemoveFromHotlist;
		this.billRate = billRate;
		this.hotlistStatusPredefine = hotlistStatusPredefine;
		this.enrollmentNextFollowupDate = enrollmentNextFollowupDate;
		this.trainingNextFollowupDate = trainingNextFollowupDate;
		this.resumeNextFollowupDate = resumeNextFollowupDate;
		this.mockNextFollowupDate = mockNextFollowupDate;
		this.referenceNextFollowupDate = referenceNextFollowupDate;
		this.preHotlistNextFollowupDate = preHotlistNextFollowupDate;
		this.importedDate = importedDate;
		this.isTerminated = isTerminated;
		this.terminatedFrom = terminatedFrom;
		this.terminationReason = terminationReason;
		this.salesFollowUps = salesFollowUps;
		this.references = references;
		this.documentses = documentses;
		this.priorities = priorities;
		this.hrFollowUps = hrFollowUps;
		this.interviewSchedules = interviewSchedules;
		this.paymentTransactions = paymentTransactions;
		this.mailDetailses = mailDetailses;
	}

	@Id

	@Column(name = "candidate_id", unique = true, nullable = false)
	public int getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(int candidateId) {
		this.candidateId = candidateId;
	}

	@Column(name = "candidate_name", nullable = false, length = 100)
	public String getCandidateName() {
		return this.candidateName;
	}

	public void setCandidateName(String candidateName) {
		this.candidateName = candidateName;
	}

	@Column(name = "contact_no", unique = true, nullable = false, length = 45)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "email_id", unique = true, nullable = false, length = 100)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "other_contactdetails", length = 100)
	public String getOtherContactdetails() {
		return this.otherContactdetails;
	}

	public void setOtherContactdetails(String otherContactdetails) {
		this.otherContactdetails = otherContactdetails;
	}

	@Column(name = "service", length = 16)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enrollment_date", length = 10)
	public Date getEnrollmentDate() {
		return this.enrollmentDate;
	}

	public void setEnrollmentDate(Date enrollmentDate) {
		this.enrollmentDate = enrollmentDate;
	}

	@Column(name = "enrollment_form_status", length = 45)
	public String getEnrollmentFormStatus() {
		return this.enrollmentFormStatus;
	}

	public void setEnrollmentFormStatus(String enrollmentFormStatus) {
		this.enrollmentFormStatus = enrollmentFormStatus;
	}

	@Column(name = "transaction_id", length = 100)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "total_amount", precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "amount_paid", precision = 10)
	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	@Column(name = "amount_due", precision = 10)
	public BigDecimal getAmountDue() {
		return this.amountDue;
	}

	public void setAmountDue(BigDecimal amountDue) {
		this.amountDue = amountDue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "offeretter_send_date", length = 10)
	public Date getOfferetterSendDate() {
		return this.offeretterSendDate;
	}

	public void setOfferetterSendDate(Date offeretterSendDate) {
		this.offeretterSendDate = offeretterSendDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tremination_date", length = 10)
	public Date getTreminationDate() {
		return this.treminationDate;
	}

	public void setTreminationDate(Date treminationDate) {
		this.treminationDate = treminationDate;
	}

	@Column(name = "emergency_contact_details", length = 200)
	public String getEmergencyContactDetails() {
		return this.emergencyContactDetails;
	}

	public void setEmergencyContactDetails(String emergencyContactDetails) {
		this.emergencyContactDetails = emergencyContactDetails;
	}

	@Column(name = "primary_skill", length = 100)
	public String getPrimarySkill() {
		return this.primarySkill;
	}

	public void setPrimarySkill(String primarySkill) {
		this.primarySkill = primarySkill;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_start_date", length = 10)
	public Date getTrainingStartDate() {
		return this.trainingStartDate;
	}

	public void setTrainingStartDate(Date trainingStartDate) {
		this.trainingStartDate = trainingStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_expected_end_date", length = 10)
	public Date getTrainingExpectedEndDate() {
		return this.trainingExpectedEndDate;
	}

	public void setTrainingExpectedEndDate(Date trainingExpectedEndDate) {
		this.trainingExpectedEndDate = trainingExpectedEndDate;
	}

	@Column(name = "batch_code", length = 45)
	public String getBatchCode() {
		return this.batchCode;
	}

	public void setBatchCode(String batchCode) {
		this.batchCode = batchCode;
	}

	@Column(name = "training_status", length = 12)
	public String getTrainingStatus() {
		return this.trainingStatus;
	}

	public void setTrainingStatus(String trainingStatus) {
		this.trainingStatus = trainingStatus;
	}

	@Column(name = "training_feedback", length = 65535)
	public String getTrainingFeedback() {
		return this.trainingFeedback;
	}

	public void setTrainingFeedback(String trainingFeedback) {
		this.trainingFeedback = trainingFeedback;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_feedback_form_send_date", length = 10)
	public Date getTrainingFeedbackFormSendDate() {
		return this.trainingFeedbackFormSendDate;
	}

	public void setTrainingFeedbackFormSendDate(Date trainingFeedbackFormSendDate) {
		this.trainingFeedbackFormSendDate = trainingFeedbackFormSendDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_feedback_receive_date", length = 10)
	public Date getTrainingFeedbackReceiveDate() {
		return this.trainingFeedbackReceiveDate;
	}

	public void setTrainingFeedbackReceiveDate(Date trainingFeedbackReceiveDate) {
		this.trainingFeedbackReceiveDate = trainingFeedbackReceiveDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ceb_test_send_date", length = 10)
	public Date getCebTestSendDate() {
		return this.cebTestSendDate;
	}

	public void setCebTestSendDate(Date cebTestSendDate) {
		this.cebTestSendDate = cebTestSendDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ceb_test_complete_date", length = 10)
	public Date getCebTestCompleteDate() {
		return this.cebTestCompleteDate;
	}

	public void setCebTestCompleteDate(Date cebTestCompleteDate) {
		this.cebTestCompleteDate = cebTestCompleteDate;
	}

	@Column(name = "ceb_test_result", length = 100)
	public String getCebTestResult() {
		return this.cebTestResult;
	}

	public void setCebTestResult(String cebTestResult) {
		this.cebTestResult = cebTestResult;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "resume_doc_send_date", length = 10)
	public Date getResumeDocSendDate() {
		return this.resumeDocSendDate;
	}

	public void setResumeDocSendDate(Date resumeDocSendDate) {
		this.resumeDocSendDate = resumeDocSendDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "resume_doc_receive_date", length = 10)
	public Date getResumeDocReceiveDate() {
		return this.resumeDocReceiveDate;
	}

	public void setResumeDocReceiveDate(Date resumeDocReceiveDate) {
		this.resumeDocReceiveDate = resumeDocReceiveDate;
	}

	@Column(name = "visa_story", length = 65535)
	public String getVisaStory() {
		return this.visaStory;
	}

	public void setVisaStory(String visaStory) {
		this.visaStory = visaStory;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tech_mock_schedule_date", length = 10)
	public Date getTechMockScheduleDate() {
		return this.techMockScheduleDate;
	}

	public void setTechMockScheduleDate(Date techMockScheduleDate) {
		this.techMockScheduleDate = techMockScheduleDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tech_mock_end_date", length = 10)
	public Date getTechMockEndDate() {
		return this.techMockEndDate;
	}

	public void setTechMockEndDate(Date techMockEndDate) {
		this.techMockEndDate = techMockEndDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mock_schedule_date", length = 10)
	public Date getMockScheduleDate() {
		return this.mockScheduleDate;
	}

	public void setMockScheduleDate(Date mockScheduleDate) {
		this.mockScheduleDate = mockScheduleDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mock_end_date", length = 10)
	public Date getMockEndDate() {
		return this.mockEndDate;
	}

	public void setMockEndDate(Date mockEndDate) {
		this.mockEndDate = mockEndDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "psr_sent_date", length = 10)
	public Date getPsrSentDate() {
		return this.psrSentDate;
	}

	public void setPsrSentDate(Date psrSentDate) {
		this.psrSentDate = psrSentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "psr_receive_date", length = 10)
	public Date getPsrReceiveDate() {
		return this.psrReceiveDate;
	}

	public void setPsrReceiveDate(Date psrReceiveDate) {
		this.psrReceiveDate = psrReceiveDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "questioner_sent_date", length = 10)
	public Date getQuestionerSentDate() {
		return this.questionerSentDate;
	}

	public void setQuestionerSentDate(Date questionerSentDate) {
		this.questionerSentDate = questionerSentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "questioner_receive_date", length = 10)
	public Date getQuestionerReceiveDate() {
		return this.questionerReceiveDate;
	}

	public void setQuestionerReceiveDate(Date questionerReceiveDate) {
		this.questionerReceiveDate = questionerReceiveDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "graduation_schedule_date", length = 10)
	public Date getGraduationScheduleDate() {
		return this.graduationScheduleDate;
	}

	public void setGraduationScheduleDate(Date graduationScheduleDate) {
		this.graduationScheduleDate = graduationScheduleDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "graduation_end_date", length = 10)
	public Date getGraduationEndDate() {
		return this.graduationEndDate;
	}

	public void setGraduationEndDate(Date graduationEndDate) {
		this.graduationEndDate = graduationEndDate;
	}

	@Column(name = "attendees", length = 200)
	public String getAttendees() {
		return this.attendees;
	}

	public void setAttendees(String attendees) {
		this.attendees = attendees;
	}

	@Column(name = "feedback", length = 65535)
	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	@Column(name = "action_required", length = 100)
	public String getActionRequired() {
		return this.actionRequired;
	}

	public void setActionRequired(String actionRequired) {
		this.actionRequired = actionRequired;
	}

	@Column(name = "alternative_phone", length = 45)
	public String getAlternativePhone() {
		return this.alternativePhone;
	}

	public void setAlternativePhone(String alternativePhone) {
		this.alternativePhone = alternativePhone;
	}

	@Column(name = "years_of_experience", length = 45)
	public String getYearsOfExperience() {
		return this.yearsOfExperience;
	}

	public void setYearsOfExperience(String yearsOfExperience) {
		this.yearsOfExperience = yearsOfExperience;
	}

	@Column(name = "current_loc", length = 200)
	public String getCurrentLoc() {
		return this.currentLoc;
	}

	public void setCurrentLoc(String currentLoc) {
		this.currentLoc = currentLoc;
	}

	@Column(name = "preferred_loc", length = 200)
	public String getPreferredLoc() {
		return this.preferredLoc;
	}

	public void setPreferredLoc(String preferredLoc) {
		this.preferredLoc = preferredLoc;
	}

	@Column(name = "visa_status", length = 400)
	public String getVisaStatus() {
		return this.visaStatus;
	}

	public void setVisaStatus(String visaStatus) {
		this.visaStatus = visaStatus;
	}

	@Column(name = "availability", length = 45)
	public String getAvailability() {
		return this.availability;
	}

	public void setAvailability(String availability) {
		this.availability = availability;
	}

	@Column(name = "priority", length = 45)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_on_hotlist", length = 10)
	public Date getDateOnHotlist() {
		return this.dateOnHotlist;
	}

	public void setDateOnHotlist(Date dateOnHotlist) {
		this.dateOnHotlist = dateOnHotlist;
	}

	@Column(name = "domain", length = 45)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reference_form_sent_date", length = 10)
	public Date getReferenceFormSentDate() {
		return this.referenceFormSentDate;
	}

	public void setReferenceFormSentDate(Date referenceFormSentDate) {
		this.referenceFormSentDate = referenceFormSentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reference_form_received_date", length = 10)
	public Date getReferenceFormReceivedDate() {
		return this.referenceFormReceivedDate;
	}

	public void setReferenceFormReceivedDate(Date referenceFormReceivedDate) {
		this.referenceFormReceivedDate = referenceFormReceivedDate;
	}

	@Column(name = "reference_check_status")
	public Boolean getReferenceCheckStatus() {
		return this.referenceCheckStatus;
	}

	public void setReferenceCheckStatus(Boolean referenceCheckStatus) {
		this.referenceCheckStatus = referenceCheckStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tentative_training_start_date", length = 10)
	public Date getTentativeTrainingStartDate() {
		return this.tentativeTrainingStartDate;
	}

	public void setTentativeTrainingStartDate(Date tentativeTrainingStartDate) {
		this.tentativeTrainingStartDate = tentativeTrainingStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "payment_mode", length = 45)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "reference_form_no", length = 100)
	public String getReferenceFormNo() {
		return this.referenceFormNo;
	}

	public void setReferenceFormNo(String referenceFormNo) {
		this.referenceFormNo = referenceFormNo;
	}

	@Column(name = "trainer_name", length = 100)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	@Column(name = "training_timing", length = 50)
	public String getTrainingTiming() {
		return this.trainingTiming;
	}

	public void setTrainingTiming(String trainingTiming) {
		this.trainingTiming = trainingTiming;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "resume_revised_date", length = 10)
	public Date getResumeRevisedDate() {
		return this.resumeRevisedDate;
	}

	public void setResumeRevisedDate(Date resumeRevisedDate) {
		this.resumeRevisedDate = resumeRevisedDate;
	}

	@Column(name = "alternate_email_id", length = 100)
	public String getAlternateEmailId() {
		return this.alternateEmailId;
	}

	public void setAlternateEmailId(String alternateEmailId) {
		this.alternateEmailId = alternateEmailId;
	}

	@Column(name = "hotlist_status")
	public Boolean getHotlistStatus() {
		return this.hotlistStatus;
	}

	public void setHotlistStatus(Boolean hotlistStatus) {
		this.hotlistStatus = hotlistStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "receiving_enrollment_date", length = 10)
	public Date getReceivingEnrollmentDate() {
		return this.receivingEnrollmentDate;
	}

	public void setReceivingEnrollmentDate(Date receivingEnrollmentDate) {
		this.receivingEnrollmentDate = receivingEnrollmentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "employment_letter_start_date", length = 10)
	public Date getEmploymentLetterStartDate() {
		return this.employmentLetterStartDate;
	}

	public void setEmploymentLetterStartDate(Date employmentLetterStartDate) {
		this.employmentLetterStartDate = employmentLetterStartDate;
	}

	@Column(name = "hotlist_candidate_name", length = 100)
	public String getHotlistCandidateName() {
		return this.hotlistCandidateName;
	}

	public void setHotlistCandidateName(String hotlistCandidateName) {
		this.hotlistCandidateName = hotlistCandidateName;
	}

	@Column(name = "resume_prep_status", length = 21)
	public String getResumePrepStatus() {
		return this.resumePrepStatus;
	}

	public void setResumePrepStatus(String resumePrepStatus) {
		this.resumePrepStatus = resumePrepStatus;
	}

	@Column(name = "mock_status", length = 45)
	public String getMockStatus() {
		return this.mockStatus;
	}

	public void setMockStatus(String mockStatus) {
		this.mockStatus = mockStatus;
	}

	@Column(name = "recruiter_name", length = 150)
	public String getRecruiterName() {
		return this.recruiterName;
	}

	public void setRecruiterName(String recruiterName) {
		this.recruiterName = recruiterName;
	}

	@Column(name = "incentive_paid_status", length = 16)
	public String getIncentivePaidStatus() {
		return this.incentivePaidStatus;
	}

	public void setIncentivePaidStatus(String incentivePaidStatus) {
		this.incentivePaidStatus = incentivePaidStatus;
	}

	@Column(name = "training_webex_account", length = 300)
	public String getTrainingWebexAccount() {
		return this.trainingWebexAccount;
	}

	public void setTrainingWebexAccount(String trainingWebexAccount) {
		this.trainingWebexAccount = trainingWebexAccount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sending_enrollment_date", length = 10)
	public Date getSendingEnrollmentDate() {
		return this.sendingEnrollmentDate;
	}

	public void setSendingEnrollmentDate(Date sendingEnrollmentDate) {
		this.sendingEnrollmentDate = sendingEnrollmentDate;
	}

	@Column(name = "supervisor_name", length = 100)
	public String getSupervisorName() {
		return this.supervisorName;
	}

	public void setSupervisorName(String supervisorName) {
		this.supervisorName = supervisorName;
	}

	@Column(name = "enrollment_Form_path", length = 200)
	public String getEnrollmentFormPath() {
		return this.enrollmentFormPath;
	}

	public void setEnrollmentFormPath(String enrollmentFormPath) {
		this.enrollmentFormPath = enrollmentFormPath;
	}

	@Column(name = "resume_path", length = 200)
	public String getResumePath() {
		return this.resumePath;
	}

	public void setResumePath(String resumePath) {
		this.resumePath = resumePath;
	}

	@Column(name = "enrollment_form_file_extension", length = 45)
	public String getEnrollmentFormFileExtension() {
		return this.enrollmentFormFileExtension;
	}

	public void setEnrollmentFormFileExtension(String enrollmentFormFileExtension) {
		this.enrollmentFormFileExtension = enrollmentFormFileExtension;
	}

	@Column(name = "resume_file_extension", length = 45)
	public String getResumeFileExtension() {
		return this.resumeFileExtension;
	}

	public void setResumeFileExtension(String resumeFileExtension) {
		this.resumeFileExtension = resumeFileExtension;
	}

	@Column(name = "enrollment_form_name", length = 100)
	public String getEnrollmentFormName() {
		return this.enrollmentFormName;
	}

	public void setEnrollmentFormName(String enrollmentFormName) {
		this.enrollmentFormName = enrollmentFormName;
	}

	@Column(name = "resume_file_name", length = 100)
	public String getResumeFileName() {
		return this.resumeFileName;
	}

	public void setResumeFileName(String resumeFileName) {
		this.resumeFileName = resumeFileName;
	}

	@Column(name = "is_remove_from_hotlist")
	public Boolean getIsRemoveFromHotlist() {
		return this.isRemoveFromHotlist;
	}

	public void setIsRemoveFromHotlist(Boolean isRemoveFromHotlist) {
		this.isRemoveFromHotlist = isRemoveFromHotlist;
	}

	@Column(name = "bill_rate", length = 45)
	public String getBillRate() {
		return this.billRate;
	}

	public void setBillRate(String billRate) {
		this.billRate = billRate;
	}

	@Column(name = "hotlist_status_predefine", length = 45)
	public String getHotlistStatusPredefine() {
		return this.hotlistStatusPredefine;
	}

	public void setHotlistStatusPredefine(String hotlistStatusPredefine) {
		this.hotlistStatusPredefine = hotlistStatusPredefine;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enrollment_next_followup_date", length = 10)
	public Date getEnrollmentNextFollowupDate() {
		return this.enrollmentNextFollowupDate;
	}

	public void setEnrollmentNextFollowupDate(Date enrollmentNextFollowupDate) {
		this.enrollmentNextFollowupDate = enrollmentNextFollowupDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_next_followup_date", length = 10)
	public Date getTrainingNextFollowupDate() {
		return this.trainingNextFollowupDate;
	}

	public void setTrainingNextFollowupDate(Date trainingNextFollowupDate) {
		this.trainingNextFollowupDate = trainingNextFollowupDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "resume_next_followup_date", length = 10)
	public Date getResumeNextFollowupDate() {
		return this.resumeNextFollowupDate;
	}

	public void setResumeNextFollowupDate(Date resumeNextFollowupDate) {
		this.resumeNextFollowupDate = resumeNextFollowupDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mock_next_followup_date", length = 10)
	public Date getMockNextFollowupDate() {
		return this.mockNextFollowupDate;
	}

	public void setMockNextFollowupDate(Date mockNextFollowupDate) {
		this.mockNextFollowupDate = mockNextFollowupDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reference_next_followup_date", length = 10)
	public Date getReferenceNextFollowupDate() {
		return this.referenceNextFollowupDate;
	}

	public void setReferenceNextFollowupDate(Date referenceNextFollowupDate) {
		this.referenceNextFollowupDate = referenceNextFollowupDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pre_hotlist_next_followup_date", length = 10)
	public Date getPreHotlistNextFollowupDate() {
		return this.preHotlistNextFollowupDate;
	}

	public void setPreHotlistNextFollowupDate(Date preHotlistNextFollowupDate) {
		this.preHotlistNextFollowupDate = preHotlistNextFollowupDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "imported_date", length = 19)
	public Date getImportedDate() {
		return this.importedDate;
	}

	public void setImportedDate(Date importedDate) {
		this.importedDate = importedDate;
	}

	@Column(name = "is_terminated", length = 45)
	public String getIsTerminated() {
		return this.isTerminated;
	}

	public void setIsTerminated(String isTerminated) {
		this.isTerminated = isTerminated;
	}

	@Column(name = "terminated_from", length = 50)
	public String getTerminatedFrom() {
		return this.terminatedFrom;
	}

	public void setTerminatedFrom(String terminatedFrom) {
		this.terminatedFrom = terminatedFrom;
	}

	@Column(name = "termination_reason", length = 65535)
	public String getTerminationReason() {
		return this.terminationReason;
	}

	public void setTerminationReason(String terminationReason) {
		this.terminationReason = terminationReason;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<SalesFollowUp> getSalesFollowUps() {
		return this.salesFollowUps;
	}

	public void setSalesFollowUps(Set<SalesFollowUp> salesFollowUps) {
		this.salesFollowUps = salesFollowUps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<Reference> getReferences() {
		return this.references;
	}

	public void setReferences(Set<Reference> references) {
		this.references = references;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<Documents> getDocumentses() {
		return this.documentses;
	}

	public void setDocumentses(Set<Documents> documentses) {
		this.documentses = documentses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "candidate_has_priority", catalog = "trmsv2_hr_sales", joinColumns = {
			@JoinColumn(name = "candidate_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "priority_id", nullable = false, updatable = false) })
	public Set<Priority> getPriorities() {
		return this.priorities;
	}

	public void setPriorities(Set<Priority> priorities) {
		this.priorities = priorities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<HrFollowUp> getHrFollowUps() {
		return this.hrFollowUps;
	}

	public void setHrFollowUps(Set<HrFollowUp> hrFollowUps) {
		this.hrFollowUps = hrFollowUps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<InterviewSchedule> getInterviewSchedules() {
		return this.interviewSchedules;
	}

	public void setInterviewSchedules(Set<InterviewSchedule> interviewSchedules) {
		this.interviewSchedules = interviewSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<PaymentTransaction> getPaymentTransactions() {
		return this.paymentTransactions;
	}

	public void setPaymentTransactions(Set<PaymentTransaction> paymentTransactions) {
		this.paymentTransactions = paymentTransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<MailDetails> getMailDetailses() {
		return this.mailDetailses;
	}

	public void setMailDetailses(Set<MailDetails> mailDetailses) {
		this.mailDetailses = mailDetailses;
	}

}
