package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documents generated by hbm2java
 */
@Entity
@Table(name = "documents", catalog = "trmsv2_hr_sales")
public class Documents implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 9722826866766757L;
	
	private Integer id;
	private Candidate candidate;
	private String fileName;
	private String filePath;
	private Date createdDate;
	private String documentType;
	private String documentFor;
	private String documentsSpecification;
	private String extension;
	private String docOtherName;

	public Documents() {
	}

	public Documents(Candidate candidate, String fileName, String filePath, Date createdDate, String documentType,
			String documentFor, String documentsSpecification, String extension) {
		this.candidate = candidate;
		this.fileName = fileName;
		this.filePath = filePath;
		this.createdDate = createdDate;
		this.documentType = documentType;
		this.documentFor = documentFor;
		this.documentsSpecification = documentsSpecification;
		this.extension = extension;
	}

	public Documents(Candidate candidate, String fileName, String filePath, Date createdDate, String documentType,
			String documentFor, String documentsSpecification, String extension, String docOtherName) {
		this.candidate = candidate;
		this.fileName = fileName;
		this.filePath = filePath;
		this.createdDate = createdDate;
		this.documentType = documentType;
		this.documentFor = documentFor;
		this.documentsSpecification = documentsSpecification;
		this.extension = extension;
		this.docOtherName = docOtherName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id", nullable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@Column(name = "file_name", nullable = false, length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_path", nullable = false, length = 200)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "document_type", nullable = false, length = 200)
	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	@Column(name = "document_for", nullable = false, length = 50)
	public String getDocumentFor() {
		return this.documentFor;
	}

	public void setDocumentFor(String documentFor) {
		this.documentFor = documentFor;
	}

	@Column(name = "documents_specification", nullable = false, length = 45)
	public String getDocumentsSpecification() {
		return this.documentsSpecification;
	}

	public void setDocumentsSpecification(String documentsSpecification) {
		this.documentsSpecification = documentsSpecification;
	}

	@Column(name = "extension", nullable = false, length = 45)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "doc_other_name", length = 100)
	public String getDocOtherName() {
		return this.docOtherName;
	}

	public void setDocOtherName(String docOtherName) {
		this.docOtherName = docOtherName;
	}

}
