package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EnrollmentFormNo generated by hbm2java
 */
@Entity
@Table(name = "enrollment_form_no", catalog = "trmsv2_hr_sales")
public class EnrollmentFormNo implements java.io.Serializable {

	/**
	 *serialVersionUID 
	 */
	private static final long serialVersionUID = 5154933964336026893L;
	
	private Integer id;
	private int enrollmentFormNumber;

	public EnrollmentFormNo() {
	}

	public EnrollmentFormNo(int enrollmentFormNumber) {
		this.enrollmentFormNumber = enrollmentFormNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "enrollment_form_number", nullable = false)
	public int getEnrollmentFormNumber() {
		return this.enrollmentFormNumber;
	}

	public void setEnrollmentFormNumber(int enrollmentFormNumber) {
		this.enrollmentFormNumber = enrollmentFormNumber;
	}

}
