package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewSchedule generated by hbm2java
 */
@Entity
@Table(name = "interview_schedule", catalog = "trmsv2_hr_sales")
public class InterviewSchedule implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 8174123668296604720L;
	
	private Integer id;
	private Candidate candidate;
	private UserProfile userProfile;
	private String vendorName;
	private String vendorContactPersonName;
	private String vendorContactPersonEmailid;
	private String vendorContactPersonPhoneNo;
	private String extension;
	private Date interviewDate;
	private String interviewTime;
	private String interviewType;
	private String interviewLocation;
	private BigDecimal interviewExpenseAmount;
	private String endClient;
	private String positionId;
	private String workLocation;
	private String billRate;
	private String feedback;
	private Integer interviewRound;
	private String interviewId;
	private Set<SalesFollowUp> salesFollowUps = new HashSet<SalesFollowUp>(0);
	private Set<ReSchedule> reSchedules = new HashSet<ReSchedule>(0);

	public InterviewSchedule() {
	}

	public InterviewSchedule(Candidate candidate, UserProfile userProfile, String vendorName,
			String vendorContactPersonName, String vendorContactPersonEmailid, String vendorContactPersonPhoneNo,
			String extension, Date interviewDate, String interviewTime, String interviewType, String interviewLocation,
			BigDecimal interviewExpenseAmount, String endClient, String positionId, String workLocation,
			String billRate, String feedback, Integer interviewRound, String interviewId,
			Set<SalesFollowUp> salesFollowUps, Set<ReSchedule> reSchedules) {
		this.candidate = candidate;
		this.userProfile = userProfile;
		this.vendorName = vendorName;
		this.vendorContactPersonName = vendorContactPersonName;
		this.vendorContactPersonEmailid = vendorContactPersonEmailid;
		this.vendorContactPersonPhoneNo = vendorContactPersonPhoneNo;
		this.extension = extension;
		this.interviewDate = interviewDate;
		this.interviewTime = interviewTime;
		this.interviewType = interviewType;
		this.interviewLocation = interviewLocation;
		this.interviewExpenseAmount = interviewExpenseAmount;
		this.endClient = endClient;
		this.positionId = positionId;
		this.workLocation = workLocation;
		this.billRate = billRate;
		this.feedback = feedback;
		this.interviewRound = interviewRound;
		this.interviewId = interviewId;
		this.salesFollowUps = salesFollowUps;
		this.reSchedules = reSchedules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id")
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "vendor_name", length = 300)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "vendor_contact_person_name", length = 100)
	public String getVendorContactPersonName() {
		return this.vendorContactPersonName;
	}

	public void setVendorContactPersonName(String vendorContactPersonName) {
		this.vendorContactPersonName = vendorContactPersonName;
	}

	@Column(name = "vendor_contact_person_emailid", length = 200)
	public String getVendorContactPersonEmailid() {
		return this.vendorContactPersonEmailid;
	}

	public void setVendorContactPersonEmailid(String vendorContactPersonEmailid) {
		this.vendorContactPersonEmailid = vendorContactPersonEmailid;
	}

	@Column(name = "vendor_contact_person_phone_no", length = 45)
	public String getVendorContactPersonPhoneNo() {
		return this.vendorContactPersonPhoneNo;
	}

	public void setVendorContactPersonPhoneNo(String vendorContactPersonPhoneNo) {
		this.vendorContactPersonPhoneNo = vendorContactPersonPhoneNo;
	}

	@Column(name = "extension", length = 45)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "interview_date", length = 10)
	public Date getInterviewDate() {
		return this.interviewDate;
	}

	public void setInterviewDate(Date interviewDate) {
		this.interviewDate = interviewDate;
	}

	@Column(name = "interview_time", length = 45)
	public String getInterviewTime() {
		return this.interviewTime;
	}

	public void setInterviewTime(String interviewTime) {
		this.interviewTime = interviewTime;
	}

	@Column(name = "interview_type", length = 45)
	public String getInterviewType() {
		return this.interviewType;
	}

	public void setInterviewType(String interviewType) {
		this.interviewType = interviewType;
	}

	@Column(name = "interview_location", length = 500)
	public String getInterviewLocation() {
		return this.interviewLocation;
	}

	public void setInterviewLocation(String interviewLocation) {
		this.interviewLocation = interviewLocation;
	}

	@Column(name = "interview_expense_amount", precision = 10)
	public BigDecimal getInterviewExpenseAmount() {
		return this.interviewExpenseAmount;
	}

	public void setInterviewExpenseAmount(BigDecimal interviewExpenseAmount) {
		this.interviewExpenseAmount = interviewExpenseAmount;
	}

	@Column(name = "end_client", length = 500)
	public String getEndClient() {
		return this.endClient;
	}

	public void setEndClient(String endClient) {
		this.endClient = endClient;
	}

	@Column(name = "position_id", length = 100)
	public String getPositionId() {
		return this.positionId;
	}

	public void setPositionId(String positionId) {
		this.positionId = positionId;
	}

	@Column(name = "work_location", length = 500)
	public String getWorkLocation() {
		return this.workLocation;
	}

	public void setWorkLocation(String workLocation) {
		this.workLocation = workLocation;
	}

	@Column(name = "bill_rate", length = 45)
	public String getBillRate() {
		return this.billRate;
	}

	public void setBillRate(String billRate) {
		this.billRate = billRate;
	}

	@Column(name = "Feedback", length = 65535)
	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	@Column(name = "interview_round")
	public Integer getInterviewRound() {
		return this.interviewRound;
	}

	public void setInterviewRound(Integer interviewRound) {
		this.interviewRound = interviewRound;
	}

	@Column(name = "interview_id", length = 45)
	public String getInterviewId() {
		return this.interviewId;
	}

	public void setInterviewId(String interviewId) {
		this.interviewId = interviewId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewSchedule")
	public Set<SalesFollowUp> getSalesFollowUps() {
		return this.salesFollowUps;
	}

	public void setSalesFollowUps(Set<SalesFollowUp> salesFollowUps) {
		this.salesFollowUps = salesFollowUps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewSchedule")
	public Set<ReSchedule> getReSchedules() {
		return this.reSchedules;
	}

	public void setReSchedules(Set<ReSchedule> reSchedules) {
		this.reSchedules = reSchedules;
	}

}
