package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MailTemplate generated by hbm2java
 */
@Entity
@Table(name = "mail_template", catalog = "trmsv2_hr_sales")
public class MailTemplate implements java.io.Serializable {

	/**
	 *serialVersionUID 
	 */
	private static final long serialVersionUID = -4479437775826186130L;
	
	private Integer id;
	private String subject;
	private String content;

	public MailTemplate() {
	}

	public MailTemplate(String subject, String content) {
		this.subject = subject;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "subject", nullable = false, length = 200)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
