package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MailDetails generated by hbm2java
 */
@Entity
@Table(name = "mail_details", catalog = "trmsv2_hr_sales")
public class MailDetails implements java.io.Serializable {

	/**
	 *serialVersionUID 
	 */
	private static final long serialVersionUID = -7165253259133973152L;
	
	private Integer id;
	private Candidate candidate;
	private UserProfile userProfile;
	private String receiverEmail;
	private String senderEmail;
	private String subject;
	private String bodyContent;
	private Date createdDate;

	public MailDetails() {
	}

	public MailDetails(UserProfile userProfile, String receiverEmail, String senderEmail, Date createdDate) {
		this.userProfile = userProfile;
		this.receiverEmail = receiverEmail;
		this.senderEmail = senderEmail;
		this.createdDate = createdDate;
	}

	public MailDetails(Candidate candidate, UserProfile userProfile, String receiverEmail, String senderEmail,
			String subject, String bodyContent, Date createdDate) {
		this.candidate = candidate;
		this.userProfile = userProfile;
		this.receiverEmail = receiverEmail;
		this.senderEmail = senderEmail;
		this.subject = subject;
		this.bodyContent = bodyContent;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id")
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "receiver_email", nullable = false, length = 200)
	public String getReceiverEmail() {
		return this.receiverEmail;
	}

	public void setReceiverEmail(String receiverEmail) {
		this.receiverEmail = receiverEmail;
	}

	@Column(name = "sender_email", nullable = false, length = 200)
	public String getSenderEmail() {
		return this.senderEmail;
	}

	public void setSenderEmail(String senderEmail) {
		this.senderEmail = senderEmail;
	}

	@Column(name = "subject", length = 500)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "body_content", length = 65535)
	public String getBodyContent() {
		return this.bodyContent;
	}

	public void setBodyContent(String bodyContent) {
		this.bodyContent = bodyContent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
