package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentTransaction generated by hbm2java
 */
@Entity
@Table(name = "payment_transaction", catalog = "trmsv2_hr_sales")
public class PaymentTransaction implements java.io.Serializable {

	/**
	 *serialVersionUID 
	 */
	private static final long serialVersionUID = -2407376198773433868L;
	
	private Integer id;
	private Candidate candidate;
	private UserProfile userProfile;
	private String transactionId;
	private BigDecimal totalAmount;
	private BigDecimal dueAmount;
	private BigDecimal paidAmount;
	private Date transactionDate;
	private Date paymentDate;
	private String paymentMode;
	private Date dueDate;

	public PaymentTransaction() {
	}

	public PaymentTransaction(Candidate candidate, UserProfile userProfile, String transactionId,
			BigDecimal totalAmount, BigDecimal paidAmount, Date transactionDate, Date paymentDate, String paymentMode) {
		this.candidate = candidate;
		this.userProfile = userProfile;
		this.transactionId = transactionId;
		this.totalAmount = totalAmount;
		this.paidAmount = paidAmount;
		this.transactionDate = transactionDate;
		this.paymentDate = paymentDate;
		this.paymentMode = paymentMode;
	}

	public PaymentTransaction(Candidate candidate, UserProfile userProfile, String transactionId,
			BigDecimal totalAmount, BigDecimal dueAmount, BigDecimal paidAmount, Date transactionDate, Date paymentDate,
			String paymentMode, Date dueDate) {
		this.candidate = candidate;
		this.userProfile = userProfile;
		this.transactionId = transactionId;
		this.totalAmount = totalAmount;
		this.dueAmount = dueAmount;
		this.paidAmount = paidAmount;
		this.transactionDate = transactionDate;
		this.paymentDate = paymentDate;
		this.paymentMode = paymentMode;
		this.dueDate = dueDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id", nullable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "transaction_id", nullable = false, length = 100)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "total_amount", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "due_amount", precision = 10)
	public BigDecimal getDueAmount() {
		return this.dueAmount;
	}

	public void setDueAmount(BigDecimal dueAmount) {
		this.dueAmount = dueAmount;
	}

	@Column(name = "paid_amount", nullable = false, precision = 10)
	public BigDecimal getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(BigDecimal paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "transaction_date", nullable = false, length = 10)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", nullable = false, length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "payment_mode", nullable = false, length = 100)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

}
