package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Priority generated by hbm2java
 */
@Entity
@Table(name = "priority", catalog = "trmsv2_hr_sales")
public class Priority implements java.io.Serializable {

	/**
	 *serialVersionUID 
	 */
	private static final long serialVersionUID = -696016021824562976L;
	
	private Integer id;
	private String priority;
	private Set<Candidate> candidates = new HashSet<Candidate>(0);
	private Set<UserProfile> userProfiles = new HashSet<UserProfile>(0);

	public Priority() {
	}

	public Priority(String priority) {
		this.priority = priority;
	}

	public Priority(String priority, Set<Candidate> candidates, Set<UserProfile> userProfiles) {
		this.priority = priority;
		this.candidates = candidates;
		this.userProfiles = userProfiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "priority", nullable = false, length = 45)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "candidate_has_priority", catalog = "trmsv2_hr_sales", joinColumns = {
			@JoinColumn(name = "priority_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "candidate_id", nullable = false, updatable = false) })
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "priorities")
	public Set<UserProfile> getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set<UserProfile> userProfiles) {
		this.userProfiles = userProfiles;
	}

}
