package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reference generated by hbm2java
 */
@Entity
@Table(name = "reference", catalog = "trmsv2_hr_sales")
public class Reference implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 420987084688332398L;
	
	private Integer referenceId;
	private Candidate candidate;
	private String projectName;
	private String projectLocation;
	private String reportingManagerName;
	private String referenceName;
	private String referencePhoneNo;
	private String referenceEmailId;
	private String teamSize;
	private String duration;

	public Reference() {
	}

	public Reference(Candidate candidate) {
		this.candidate = candidate;
	}

	public Reference(Candidate candidate, String projectName, String projectLocation, String reportingManagerName,
			String referenceName, String referencePhoneNo, String referenceEmailId, String teamSize, String duration) {
		this.candidate = candidate;
		this.projectName = projectName;
		this.projectLocation = projectLocation;
		this.reportingManagerName = reportingManagerName;
		this.referenceName = referenceName;
		this.referencePhoneNo = referencePhoneNo;
		this.referenceEmailId = referenceEmailId;
		this.teamSize = teamSize;
		this.duration = duration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reference_id", unique = true, nullable = false)
	public Integer getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(Integer referenceId) {
		this.referenceId = referenceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id", nullable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@Column(name = "project_name", length = 200)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_location", length = 300)
	public String getProjectLocation() {
		return this.projectLocation;
	}

	public void setProjectLocation(String projectLocation) {
		this.projectLocation = projectLocation;
	}

	@Column(name = "reporting_manager_name", length = 100)
	public String getReportingManagerName() {
		return this.reportingManagerName;
	}

	public void setReportingManagerName(String reportingManagerName) {
		this.reportingManagerName = reportingManagerName;
	}

	@Column(name = "reference_name", length = 200)
	public String getReferenceName() {
		return this.referenceName;
	}

	public void setReferenceName(String referenceName) {
		this.referenceName = referenceName;
	}

	@Column(name = "reference_phone_no", length = 45)
	public String getReferencePhoneNo() {
		return this.referencePhoneNo;
	}

	public void setReferencePhoneNo(String referencePhoneNo) {
		this.referencePhoneNo = referencePhoneNo;
	}

	@Column(name = "reference_email_id", length = 100)
	public String getReferenceEmailId() {
		return this.referenceEmailId;
	}

	public void setReferenceEmailId(String referenceEmailId) {
		this.referenceEmailId = referenceEmailId;
	}

	@Column(name = "team_size", length = 45)
	public String getTeamSize() {
		return this.teamSize;
	}

	public void setTeamSize(String teamSize) {
		this.teamSize = teamSize;
	}

	@Column(name = "duration", length = 45)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

}
