package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReSchedule generated by hbm2java
 */
@Entity
@Table(name = "re_schedule", catalog = "trmsv2_hr_sales")
public class ReSchedule implements java.io.Serializable {

	/**
	 *serialVersionUID 
	 */
	private static final long serialVersionUID = 1264029936685707569L;
	
	private Integer id;
	private InterviewSchedule interviewSchedule;
	private Date interviewDate;
	private String interviewTime;
	private Integer interviewRound;
	private String interviewType;
	private String interviewLocation;

	public ReSchedule() {
	}

	public ReSchedule(InterviewSchedule interviewSchedule, Date interviewDate, String interviewTime,
			Integer interviewRound, String interviewType, String interviewLocation) {
		this.interviewSchedule = interviewSchedule;
		this.interviewDate = interviewDate;
		this.interviewTime = interviewTime;
		this.interviewRound = interviewRound;
		this.interviewType = interviewType;
		this.interviewLocation = interviewLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interview_schedule_id")
	public InterviewSchedule getInterviewSchedule() {
		return this.interviewSchedule;
	}

	public void setInterviewSchedule(InterviewSchedule interviewSchedule) {
		this.interviewSchedule = interviewSchedule;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "interview_date", length = 10)
	public Date getInterviewDate() {
		return this.interviewDate;
	}

	public void setInterviewDate(Date interviewDate) {
		this.interviewDate = interviewDate;
	}

	@Column(name = "interview_time", length = 45)
	public String getInterviewTime() {
		return this.interviewTime;
	}

	public void setInterviewTime(String interviewTime) {
		this.interviewTime = interviewTime;
	}

	@Column(name = "interview_round")
	public Integer getInterviewRound() {
		return this.interviewRound;
	}

	public void setInterviewRound(Integer interviewRound) {
		this.interviewRound = interviewRound;
	}

	@Column(name = "interview_type", length = 45)
	public String getInterviewType() {
		return this.interviewType;
	}

	public void setInterviewType(String interviewType) {
		this.interviewType = interviewType;
	}

	@Column(name = "interview_location", length = 500)
	public String getInterviewLocation() {
		return this.interviewLocation;
	}

	public void setInterviewLocation(String interviewLocation) {
		this.interviewLocation = interviewLocation;
	}

}
