package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesFollowUp generated by hbm2java
 */
@Entity
@Table(name = "sales_follow_up", catalog = "trmsv2_hr_sales")
public class SalesFollowUp implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -1610053187613413844L;
	
	private Integer salesFollowupId;
	private Candidate candidate;
	private InterviewSchedule interviewSchedule;
	private UserProfile userProfile;
	private Date followUpDate;
	private String followUpRemarks;
	private String followUpType;
	private Date nextFollowUpDate;

	public SalesFollowUp() {
	}

	public SalesFollowUp(Candidate candidate, UserProfile userProfile, Date followUpDate, String followUpRemarks) {
		this.candidate = candidate;
		this.userProfile = userProfile;
		this.followUpDate = followUpDate;
		this.followUpRemarks = followUpRemarks;
	}

	public SalesFollowUp(Candidate candidate, InterviewSchedule interviewSchedule, UserProfile userProfile,
			Date followUpDate, String followUpRemarks, String followUpType, Date nextFollowUpDate) {
		this.candidate = candidate;
		this.interviewSchedule = interviewSchedule;
		this.userProfile = userProfile;
		this.followUpDate = followUpDate;
		this.followUpRemarks = followUpRemarks;
		this.followUpType = followUpType;
		this.nextFollowUpDate = nextFollowUpDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sales_followup_id", unique = true, nullable = false)
	public Integer getSalesFollowupId() {
		return this.salesFollowupId;
	}

	public void setSalesFollowupId(Integer salesFollowupId) {
		this.salesFollowupId = salesFollowupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id", nullable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interview_schedule_id")
	public InterviewSchedule getInterviewSchedule() {
		return this.interviewSchedule;
	}

	public void setInterviewSchedule(InterviewSchedule interviewSchedule) {
		this.interviewSchedule = interviewSchedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "follow_up_date", nullable = false, length = 10)
	public Date getFollowUpDate() {
		return this.followUpDate;
	}

	public void setFollowUpDate(Date followUpDate) {
		this.followUpDate = followUpDate;
	}

	@Column(name = "follow_up_remarks", nullable = false, length = 500)
	public String getFollowUpRemarks() {
		return this.followUpRemarks;
	}

	public void setFollowUpRemarks(String followUpRemarks) {
		this.followUpRemarks = followUpRemarks;
	}

	@Column(name = "follow_up_type", length = 45)
	public String getFollowUpType() {
		return this.followUpType;
	}

	public void setFollowUpType(String followUpType) {
		this.followUpType = followUpType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "next_follow_up_date", length = 10)
	public Date getNextFollowUpDate() {
		return this.nextFollowUpDate;
	}

	public void setNextFollowUpDate(Date nextFollowUpDate) {
		this.nextFollowUpDate = nextFollowUpDate;
	}

}
