package com.ayantsoft.trmsv3.hibernate.pojo;
// Generated 14 Sep, 2017 12:05:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Visa generated by hbm2java
 */
@Entity
@Table(name = "visa", catalog = "trmsv2_hr_sales")
public class Visa implements java.io.Serializable {

	/**
	 *serialVersionUID 
	 */
	private static final long serialVersionUID = -431922826418790499L;
	
	private Integer id;
	private String visaName;

	public Visa() {
	}

	public Visa(String visaName) {
		this.visaName = visaName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "visa_name", nullable = false, length = 45)
	public String getVisaName() {
		return this.visaName;
	}

	public void setVisaName(String visaName) {
		this.visaName = visaName;
	}

}
